void Tischflaeche();
void TischflaechemitTextur();
void MittelLochVerkleidung();
void EckLochVerkleidung();
void MittelLochInnenverkleidung();
void EckLochInnenverkleidung();
void WoodBand(GLfloat, GLint, GLfloat, GLfloat);
void WoodBandOT(GLfloat, GLint);
void Banden(GLint richtung, GLint Multiply);
void MittelLochRand();
void EckLochRand();
void Diamant(GLfloat,GLfloat,GLfloat);
